[build]
  publish = "."

[build.environment]
  NETLIFY_DRAWER = "off"
  NETLIFY_TOOLBAR = "off"
  NETLIFY_PREVIEWS = "off"
  DISABLE_NETLIFY_DRAWER = "true"

[[redirects]]
  from = "/sultana-hafeja-set"
  to = "/sultana-hafeja-set/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "frame-src 'none'; child-src 'none'; object-src 'none';"

[context.production.environment]
  NETLIFY_DRAWER = "off"
  NETLIFY_TOOLBAR = "off"
  NETLIFY_PREVIEWS = "off"

[context.deploy-preview.environment]
  NETLIFY_DRAWER = "off"
  NETLIFY_TOOLBAR = "off"
  NETLIFY_PREVIEWS = "off"

[context.branch-deploy.environment]
  NETLIFY_DRAWER = "off"
  NETLIFY_TOOLBAR = "off"
  NETLIFY_PREVIEWS = "off"
